//
//  EthosApiEndPoints.swift
//  Ethos
//
//  Created by mac on 08/08/23.
//

import Foundation

struct EthosApiEndPoints {
    static let login = "/login"
    static let socialLogin = "/socialLogin"
    static let getArticles = "/getArticles"
    static let getViewAllArticles = "/getViewAllArticles"
    static let getArticleDetail = "/getArticle/"
    static let getBrands = "/getBrands"
    static let getAds = "/getAds"
    static let getFilters = "/getFilters"
    static let getBrandsForSellOrTrade = "/products/brands"
    static let formBrands = "/formbrands"
    static let getBanners = "/getSectionBanner"
    static let getArticleCategories = "/getArticleCategories"
    static let getGlossary = "/getGlossary"
    static let generateOTP = "/otp/generate/"
    static let generateOTPRegister = "/generateregistrationotp/"
    static let getSellQuotation = "/sellInfo"
    static let getTradeQuotation = "/tradeInfo"
    static let verifyOTPRegister = "/verifyregistrationotp/"
    static let verifyOTP = "/otp/verify/"
    static let getCategories = "/categories"
    static let getProductFromCategory = "/categories/"
    static let saveCustomerServiceEnquiryMobileApp = "/saveCustomerServiceEnquiryMobileApp"
    static let customerServicePickup = "/customerServicePickup"
    static let storePageLead = "/storePageLead"
    static let updateCustomerProfileImage = "/customers/profileImage"
    static let contactus = "/contactus"
    static let checkOurSellingPrice = "/checkSellingPrice"
    static let registerUser = "/customerregistration"
    static let sendResetLink = "/customers/password/resetlink"
    static let getCategoriesList = "/categories/list"
    static let changePassword = "/customers/me/password"
    static let getProducts = "/products"
    static let betterTogether = "/better-together/"
    static let getFiltersByAttribute = "/getFiltersByAttr"
    static let getFilteredProducts = "/filterProduct"
    static let getProductsNewArrival = "/products/newArrival"
    static let getStores = "/getStores"
    static let getTopStores = "/topstores"
    static let getAllStores = "/getallstores"
    static let getAppSettings = "/getappsettings"
    static let getNewBoutiques = "/new-boutiques"
    static let getCustomerDetails = "/customers/me"
    static let customers = "/customers/"
    static let getCustomerPointBalance = "/getCustomerPointBalance/"
    static let getSearchSuggestion = "/searchsuggestion"
    static let getPopularSearch = "/popularsearch"
    static let schedulePickupBrands = "/schedule-pickup-brands"
    static let requestACallBackBrands = "/request-callback-brands"
    static let getFAQ = "/helpCenter/faqs"
    static let getFAQCategories = "/helpCenter/categories"
    static let helpSupport = "/help-support"
    static let getUrlType = "/getUrlType"
    static let getCustomerPurchaseHistory = "/getCustomerPurchaseHistory/"
}
